export const TEXTS = {
  dashboard: {
    focus: 'Focus',
    shortBreak: 'Short',
    longBreak: 'Long',
    start: 'START SESSION',
    pause: 'PAUSE SESSION',
    resume: 'RESUME',
    stop: 'STOP',
    skip: 'SKIP',
    round: 'Round',
  },
  sidebar: {
    games: 'Games',
    stats: 'Stats',
    achievements: 'Achievements',
    music: 'Music',
    settings: 'Settings',
    support: 'Support',
  },
  settings: {
    title: 'Settings',
    save: 'Save Changes',
    timer: 'Timer',
    display: 'Display',
    audio: 'Audio',
    shortcuts: 'Shortcuts',
    focus: 'Focus',
    shortBreak: 'Short Break',
    longBreak: 'Long Break',
    autoStartBreaks: 'Auto-start Breaks',
    autoStartPomodoros: 'Auto-start Pomodoros',
    longBreakInterval: 'Long Break Interval',
    theme: 'Theme',
    dark: 'Dark',
    light: 'Light',
    accentColor: 'Accent Color',
    bgImage: 'Background Image URL',
    blurIntensity: 'Blur Intensity',
    timeFormat: 'Time Format',
    twentyFourHour: '24-hour',
    twelveHour: '12-hour',
    soundEnabled: 'Sound Enabled',
    volume: 'Volume',
    reset: 'Reset',
    workflow: 'Workflow & Automation',
    autoStartFocus: 'Auto-start Focus',
    clock24: '24-Hour Clock',
    auditory: 'Auditory Experience',
    masterVolume: 'Master Volume',
    testAlarm: 'Test Focus Alarm',
    visual: 'Visual Sanctuary',
    accentTheme: 'Accent Theme',
    glassBlur: 'Glass Blur Intensity',
    removeBg: 'Remove Background',
    uploadFile: 'Upload File',
  },
  profile: {
    loading: 'Loading profile...',
    usernameShort: 'Username too short',
    invalidUrl: 'Invalid image URL (use https://)',
    updateSuccess: 'Profile updated successfully',
    updateFailed: 'Failed to update profile',
    deletePrompt: 'To delete your account, please enter your password:',
    deleteFailed: 'Failed to delete account. Incorrect password?',
    usernamePlaceholder: 'Username',
    avatarPlaceholder: 'Avatar Image URL',
    level: 'Level',
    logout: 'Logout',
    deleteAccount: 'Delete Account',
    loginToView: 'To view your profile, you need an account.',
  },
  header: {
    install: 'Install',
    verified: 'Verified',
  },
  tasks: {
    missionLog: 'Mission Log',
    nextObjective: "What's the next objective?",
    estPomos: 'Est. Pomos',
    general: 'General',
  },
  gamification: {
    achievements: 'Achievements',
    leaderboard: 'Leaderboard',
    noRankings: 'No rankings available',
  },
  stats: {
    insights: 'Insights',
    pomodoros: 'Pomodoros',
    completed: 'Completed',
    currentStreak: 'Current Streak',
    days: 'Days',
    best: 'Best',
    level: 'Level',
    currentRank: 'Current rank',
    experience: 'Experience',
    totalXp: 'Total XP',
    currentLevel: 'Current Level',
    xp: 'Experience (XP)',
    focusStreak: 'Focus Streak',
    totalPomodoros: 'Total Pomodoros',
    loginToView: 'To view achievements and statistics, you need an account.',
  },
  tags: {
    selectCategory: 'Select Category',
    noCategory: 'No Category',
    deleteConfirm: 'Are you sure you want to delete this tag?',
    tagName: 'Tag name',
    addTag: 'Add category',
  },
  auth: {
    loginRequired: 'You must log in',
  },
};
